# service config
chain_id: irita
node_rpc_addr: http://172.18.68.132:26657
node_grpc_addr: http://172.18.68.132:9090
key_name: sp
key_path: /mnt/d/gocode/src/now/sp.txt
address: iaa1mxatp6h7huukny9uha8u45qkfas2f6lgpa4nhw
fee: 4stake
key_algorithm: SM2